const EMPTY_HOUSES = {
  kicker: 'Empty',
  title: 'Nothing listed yet.',
  copy: 'Collections expand from the atelier — or begin a strand in the studio.',
  primaryCta: { label: 'Customization', to: '/customize' },
  secondaryCta: { label: 'Shop All', to: '/shop' },
};

const PAGES_DEFAULTS = {
  shop: {
    eyebrow: 'The collection',
    title: 'Shop All',
    body: 'Ready-made pieces across crystals, rudraksha and gemstones.',
    familyBody: 'Ready-made pieces from the house of {house}.',
    action: 'Customization →',
    to: '/customize',
    empty: {
      kicker: 'Empty',
      title: 'No pieces listed yet.',
      copy: 'Begin a custom strand, or enter one of the three houses.',
      primaryCta: { label: 'Customization', to: '/customize' },
      secondaryCta: { label: 'The houses', to: '/crystals' },
    },
  },
  family: {
    shopAction: 'Shop all →',
    shopTo: '/shop',
    piecesEyebrow: 'The collection',
    piecesTitle: 'Pieces',
    piecesBody: '{count} {pieces} from this house.',
    piecesAction: 'Customization →',
    piecesTo: '/customize',
    empty: EMPTY_HOUSES,
  },
  category: {
    action: 'Customization →',
    to: '/customize',
    missing: {
      kicker: 'Missing',
      title: 'Collection not found.',
      copy: 'This category is not published yet.',
      primaryCta: { label: 'Shop All', to: '/shop' },
      secondaryCta: { label: 'Customization', to: '/customize' },
    },
    empty: {
      kicker: 'Empty',
      title: 'No pieces here yet.',
      copy: 'The atelier will add them — or compose a strand in the studio.',
      primaryCta: { label: 'Customization', to: '/customize' },
      secondaryCta: { label: 'Shop All', to: '/shop' },
    },
  },
  product: {
    missing: {
      kicker: 'Missing',
      title: 'Piece not found.',
      copy: 'This work is no longer listed. Walk the houses, or begin in the studio.',
      primaryCta: { label: 'Shop All', to: '/shop' },
      secondaryCta: { label: 'Customization', to: '/customize' },
    },
  },
  customize: {
    steps: [
      {
        eyebrow: 'The studio',
        title: 'Choose a purpose',
        body: 'Begin with why you wear it. One purpose opens its intentions — calm, abundance, protection, or love.',
      },
      {
        eyebrow: 'Step 02 · Intention',
        title: 'Choose an intention',
        body: 'Click an intention. Its crystals open so you can keep or release them, then continue.',
      },
      {
        eyebrow: 'Step 03 · Birth',
        title: 'Date of birth',
        body: 'Mulank is taken from the day. The strand is composed to that number.',
      },
      {
        eyebrow: 'Step 04 · Zodiac',
        title: 'Zodiac beads',
        body: 'Your sign’s stone is added beside the charm. The repeating pattern stays fixed.',
      },
      {
        eyebrow: 'Step 05 · Name',
        title: 'Charm & thread',
        body: 'Sriyantra or Om at the clasp. Korean elastic is free size; steel core is sized to the wrist.',
      },
      {
        eyebrow: 'Step 06 · Review',
        title: 'Review & order',
        body: 'Confirm the composition. Place the piece in your bag, then continue to checkout.',
      },
    ],
  },
  aboutPage: {
    eyebrow: 'Kuberstones',
    action: 'Customization →',
    to: '/customize',
    image: '',
  },
  collections: {
    eyebrow: 'The rooms',
    title: 'Collections',
    body: 'Rule-based rooms that stay in step with what you sell — best sellers, new arrivals, and the rest.',
    action: 'Enter →',
    empty: {
      kicker: 'Empty',
      title: 'No collections published yet.',
      copy: 'Rooms appear here as you create them in admin.',
      primaryCta: { label: 'Shop All', to: '/shop' },
      secondaryCta: { label: 'Customization', to: '/customize' },
    },
  },
  cart: {
    eyebrow: 'The atelier',
    title: 'Bag',
    emptyBody: 'Your bag is empty. Begin a custom strand, or walk the three houses until a piece finds you.',
    filledBody: '{count} {pieces} held for checkout — ready-made or composed in the studio.',
    action: 'Shop all →',
    to: '/shop',
    empty: {
      kicker: 'Empty',
      title: 'Your bag is empty.',
      copy: 'Begin a custom strand or browse the houses.',
      primaryCta: { label: 'Customization', to: '/customize' },
      secondaryCta: { label: 'Shop All', to: '/shop' },
    },
  },
  wishlist: {
    eyebrow: 'The atelier',
    title: 'Wishlist',
    emptyBody: 'Save pieces you love. They wait here until you are ready.',
    filledBody: '{count} saved {pieces} — held here until you are ready.',
    action: 'Shop all →',
    to: '/shop',
    empty: {
      kicker: 'Empty',
      title: 'Nothing saved yet.',
      copy: 'Begin in the houses, or compose a strand in the studio.',
      primaryCta: { label: 'Shop All', to: '/shop' },
      secondaryCta: { label: 'Customization', to: '/customize' },
    },
  },
  checkout: {
    title: 'Checkout',
    body: 'Confirm the delivery address, apply a coupon if you have one, then choose payment and place the order.',
    emptyTitle: 'Nothing to check out',
    emptyBody: 'Add a piece first.',
    submitLabel: 'Place order',
    submitBusy: 'Placing…',
    summaryTitle: 'Bill summary',
  },
  login: {
    eyebrow: 'The atelier',
    title: 'Sign in',
    body: 'One account for the store and the atelier. Your bag and wishlist travel with you.',
    action: 'Create account →',
    to: '/register',
    cardKicker: 'Welcome back',
    cardTitle: 'Enter the house.',
    submitLabel: 'Sign in',
    submitBusy: 'Signing in…',
    footer: 'New here?',
    footerLink: 'Create an account',
  },
  register: {
    eyebrow: 'The atelier',
    title: 'Create account',
    body: 'Join the house. A custom strand, a saved piece, and the atelier list — kept under one name.',
    action: 'Sign in →',
    to: '/login',
    cardKicker: 'Begin',
    cardTitle: 'A place in the house.',
    submitLabel: 'Create account',
    submitBusy: 'Creating…',
    footer: 'Already with us?',
    footerLink: 'Sign in',
  },
  account: {
    eyebrow: 'The atelier',
    title: 'Account',
    guestBody: 'Your orders and atelier stay under one name.',
    action: 'Shop all →',
    to: '/shop',
    cardKicker: 'Session',
    cardTitle: 'Your house.',
    ordersEyebrow: 'The collection',
    ordersTitle: 'Orders',
    ordersLoading: 'Fetching your orders.',
    ordersEmptyBody: 'No orders yet. Begin a custom strand or walk the houses.',
    ordersFilledBody: '{count} {orders} held in the atelier.',
    ordersAction: 'Customization →',
    placedKicker: 'Placed',
    placedBody: 'Order {number} is placed. If you paid online, the payment is being confirmed.',
    empty: {
      kicker: 'Empty',
      title: 'No orders yet.',
      copy: 'Begin a custom strand, or choose a ready-made piece from the houses.',
      primaryCta: { label: 'Customization', to: '/customize' },
      secondaryCta: { label: 'Shop All', to: '/shop' },
    },
  },
  notFound: {
    title: 'Page not found',
    body: 'This path is not part of the Kuberstones house.',
    cta: 'Return home',
    to: '/',
  },
  legal: {
    returns: {
      title: 'Return Policy',
      eyebrow: 'Customer care',
      body: 'Return eligibility depends on the nature and condition of the product. Personalized pieces may not be returnable once preparation has started.',
      sections: [
        {
          heading: 'Personalized and customized pieces',
          body: 'Change-of-mind returns may not be available for products that are personalized, customized, prepared or energized specifically for a customer once preparation has started.',
        },
        {
          heading: 'When a return may be requested',
          body: 'Wrong product, transit damage, missing parts, material difference from the description, or other eligible defects covered by applicable law may be reviewed after verification.',
        },
        {
          heading: 'How to request',
          body: 'Contact support as soon as reasonably possible after delivery with the order number, photographs or video where relevant, and a clear description of the issue.',
        },
      ],
    },
    privacy: {
      title: 'Privacy Policy',
      eyebrow: 'Legal',
      body: 'Kuberstones uses personal information for order processing, customization, support, delivery, payments, fraud prevention and legally required compliance.',
      sections: [
        {
          heading: 'Information we may hold',
          body: 'Name, contact details, delivery address, order details, payment-related information handled by payment providers, and voluntarily provided customization details such as date of birth, zodiac sign, moon sign, purpose or intention.',
        },
        {
          heading: 'Service providers',
          body: 'Payment processors, logistics partners, technology providers and communication providers may process information only for relevant services and subject to their own terms.',
        },
        {
          heading: 'Your questions',
          body: 'Customers may contact Kuberstones regarding questions about their personal information, subject to applicable law and verification requirements.',
        },
      ],
    },
    terms: {
      title: 'Terms & Conditions',
      eyebrow: 'Legal',
      body: 'By using the Kuberstones website or placing an order, customers agree to use the website lawfully and provide accurate information.',
      sections: [
        {
          heading: 'Spiritual and traditional information',
          body: 'Information on the website is for informational and belief-based purposes. Kuberstones does not represent that any product will guarantee a particular financial, medical, relationship, career, personal or spiritual result.',
        },
        {
          heading: 'Catalogue and natural products',
          body: 'Natural products may differ slightly from photographs because of natural variation, lighting, screen settings and individual characteristics.',
        },
        {
          heading: 'Governing law',
          body: 'These terms are subject to applicable laws of India. Nothing here is intended to exclude consumer rights that cannot lawfully be excluded.',
        },
      ],
    },
    shipping: {
      title: 'Shipping & Delivery Policy',
      eyebrow: 'Customer care',
      body: 'How Kuberstones processes, prepares and delivers ready-made and customized orders.',
      sections: [
        { heading: 'When we process an order', body: 'Orders are processed after successful payment or confirmation, subject to product availability and any customization or preparation requirements. Customized spiritual bracelets may need extra preparation time compared with ready-to-ship products.' },
        { heading: 'Timelines can change', body: 'Delivery timelines can be affected by courier operations, weather, holidays, remote locations, incorrect addresses, customer unavailability or other circumstances outside our reasonable control.' },
        { heading: 'Your address and contact details', body: 'Customers should provide a complete and accurate delivery address and reachable contact details. If a parcel is returned because of an incorrect address or repeated delivery failure, additional shipping arrangements may be required.' },
        { heading: 'On delivery', body: 'Inspect the package on delivery and contact Kuberstones promptly if there is visible transit damage or an order discrepancy.' },
      ],
    },
    exchanges: {
      title: 'Exchange Policy',
      eyebrow: 'Customer care',
      body: 'When Kuberstones may exchange or replace a piece, and what natural variation is not a defect.',
      sections: [
        { heading: 'How we evaluate exchanges', body: 'Exchange requests are evaluated based on the product and reason for the request. Customized or prepared products are generally not eligible for exchange due to change of mind once preparation has started.' },
        { heading: 'Incorrect, damaged or not-as-described products', body: 'If an incorrect, damaged or materially not-as-described product is received, Kuberstones may offer replacement, exchange, refund or another appropriate remedy after verification.' },
        { heading: 'Natural variation', body: 'Natural variations in colour, pattern, texture, shape, inclusions and markings in crystals, gemstones and Rudraksha are not by themselves evidence of a defect.' },
      ],
    },
    refunds: {
      title: 'Refund & Cancellation Policy',
      eyebrow: 'Customer care',
      body: 'When an order may be cancelled, and how approved refunds are processed.',
      sections: [
        { heading: 'Cancellation', body: 'Orders may be cancelled before processing or customization begins. Once a customized product has entered preparation, cancellation may no longer be possible.' },
        { heading: 'Approved refunds', body: 'Where a refund is approved, the amount and method depend on the reason and the payment method used. Approved refunds are generally processed to the original payment method.' },
        { heading: 'If we cannot fulfil an order', body: 'If an order cannot be fulfilled due to stock or operational reasons, Kuberstones may cancel the affected order and refund amounts actually received for that order.' },
        { heading: 'Statutory rights', body: 'Nothing in this policy limits any statutory consumer rights that cannot lawfully be excluded.' },
      ],
    },
    maintenance: {
      title: 'Website Maintenance',
      eyebrow: 'Service availability',
      body: 'When the Kuberstones website, catalogue or services may be unavailable, and how orders are confirmed.',
      sections: [
        { heading: 'Availability', body: 'Website features may occasionally be unavailable because of maintenance, upgrades, technical issues, third-party interruptions or circumstances beyond our reasonable control.' },
        { heading: 'Changes to the site', body: 'We may update, suspend or discontinue any website feature, product, price, offer or service when necessary.' },
        { heading: 'Orders are subject to confirmation', body: 'Product availability, pricing, delivery timelines and offers are subject to change. An order is subject to acceptance and confirmation by Kuberstones.' },
      ],
    },
    grievance: {
      title: 'Contact & Grievance Redressal',
      eyebrow: 'Customer care',
      body: 'How to reach Kuberstones and raise a complaint.',
      sections: [
        { heading: 'How we handle complaints', body: 'Kuberstones aims to resolve customer questions and complaints fairly and efficiently. Include your order number, registered contact details and a concise description of the issue.' },
      ],
    },
  },
};

const FOOTER_DEFAULTS = {
  bannerImage: '',
  logo: '',
  kicker: 'The atelier',
  title: 'New strands, written quietly.',
  copy: 'Collections, studio notes, and the occasional ritual. No noise.',
  cta: 'Contact us',
  brandName: 'KUBERSTONES',
  legalEntity: 'Nexxgenn Technology',
  blurb: 'A modern D2C spiritual lifestyle brand offering Crystal Beads, Spiritual Bracelets, Gemstones and Rudraksha — personalized around purpose and intention.',
  tagline: 'Crystals. Gemstones. Rudraksha. Personalized With Purpose.',
  email: 'mailto:hello@kuberstones.com',
  instagram: 'https://instagram.com',
  location: 'India · Made to order',
  address: '',
  supportPhone: '',
  grievanceOfficer: '',
  grievanceEmail: '',
  copyright: 'Kuberstones. A brand by Nexxgenn Technology. All rights reserved.',
  disclaimer: 'Spiritual and astrological information is for informational and belief-based purposes. Kuberstones does not promise guaranteed life outcomes.',
  shopHeading: 'Shop',
  careHeading: 'Customer Care',
  legalHeading: 'Legal',
  contactLabel: 'Contact Us',
  shopLinks: [
    { to: '/about', label: 'About Kuberstones' },
    { to: '/crystals', label: 'Crystal Beads' },
    { to: '/customize', label: 'Spiritual Bracelets' },
    { to: '/gemstones', label: 'Gemstones' },
    { to: '/rudraksha', label: 'Rudraksha' },
    { to: '/customize/purpose', label: 'Shop by Purpose' },
  ],
  careLinks: [
    { to: '/shipping', label: 'Shipping & Delivery' },
    { to: '/returns', label: 'Returns' },
    { to: '/exchanges', label: 'Exchanges' },
    { to: '/refunds', label: 'Refunds & Cancellations' },
    { to: '/faq', label: 'FAQs' },
    { to: '/account', label: 'Track Order' },
  ],
  legalLinks: [
    { to: '/privacy', label: 'Privacy Policy' },
    { to: '/terms', label: 'Terms & Conditions' },
    { to: '/maintenance', label: 'Website Maintenance' },
    { to: '/grievance', label: 'Contact & Grievance Redressal' },
  ],
};

const CONTACT_DEFAULTS = {
  eyebrow: 'The atelier',
  title: 'Contact us',
  body: 'Tell us how we may help — a piece, a custom strand, or a quiet question.',
  submitLabel: 'Send the note',
  sentKicker: 'Received',
  sentTitle: 'We have your note.',
  sentBody: 'Thank you, {name}. The house will write back to {email}.',
};

export { PAGES_DEFAULTS, FOOTER_DEFAULTS, CONTACT_DEFAULTS };
